version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: ecommerce-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "#M1a2l3i4"
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: ecommerce-api
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:#M1a2l3i4@postgres:5432/ecommerce_db"
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: ecommerce-nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data: